sonar.projectKey=anytime-trial_anytime-markdown
sonar.organization=anytime-trial
sonar.projectName=anytime-markdown

sonar.sources=packages/editor-core/src,packages/web-app/src,packages/vscode-extension/src
sonar.tests=packages/editor-core/src/__tests__,packages/web-app/src/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/*.config.js,**/*.config.ts,**/dist/**,**/.next/**

sonar.javascript.lcov.reportPaths=packages/editor-core/coverage/lcov.info
sonar.typescript.tsconfigPaths=packages/editor-core/tsconfig.json,packages/web-app/tsconfig.json
